CREATE DATABASE $DB_NAME;
CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_ROOTPWD';
GRANT ALL ON Data.* TO '$DB_USER'@'%';
FLUSH PRIVILEGES;
ALTER USER '$DB_ROOT'@'localhost' IDENTIFIED BY '$DB_ROOTPWD';